export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'DELETE_CURRENT';
export const FILTER_ITEMS = 'FILTER_ITEMS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_ITEMS = 'GET_ITEMS';
export const LOGIN_SUCCESSFUl = 'LOGIN_SUCCESSFUl';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT= 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERROR';
export const ITEM_ERROR = 'ITEM_ERROR';
export const PERCENTAGE = 'PERCENTAGE';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';
export const LOGIN_ADMIN_SUCCESSFUL = 'LOGIN_ADMIN_SUCCESSFUl';
//Cart Types
export const GET_CART = 'GET_CART';
export const ADD_ITEM_INCART = 'ADD_ITEM_INCART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const EDIT_ITEM_INCART = 'EDIT_ITEM_INCART';
export const POST_CART = 'POST_CART';
export const CART_ERROR = 'CART_ERROR';
export const CHECKOUT_CART = 'CHECKOUT_CART';
export const CHECKOUT_AUTH = 'CHECKOUT_AUTH';
export const EDIT_DB_CART_LOGOUT = 'EDIT_DB_CART';
export const UPDATE_CART = 'UPDATE_CART';
//Order Type
export const GET_ORDERS = 'GET_ORDERS';